### ISSUE TITLE
Custom PR comment template gone

### ISSUE THREAD

**Issue by timkrins** [ctrf-io/github-test-reporter#40]
Hello,

We were using the custom template option for the PR comment - and I thought I had broken something when the PR comment reverted back to the default.

Turns out I think it was removed purposefully in #38

I will fix our own repo to `github-actions-ctrf@0.0.42` for now.

But - can I bring it back?

Also, architecture-wise, can I suggest that _all_ of the templates are rendered via handlebars - even the default ones - as this would probably result in less code, and super-simple customisable functionality.

**Comment by Ma11hewThomas** [comment]
Hello @timkrins,

Apologies for the oversight — you're right that the pr-message argument was mistakenly removed.

When we introduced the ability to post all summary views, including custom ones, to pull requests using the --pull-request argument and the new pull-request method, the --pr-message argument was inadvertently removed without a deprecation notice.

I've restored it in #41 version (v0.0.45).

Thank you!
