### ISSUE TITLE
Update existing comment on PR checks

### ISSUE THREAD

**Issue by mattcat10** [ctrf-io/github-test-reporter#51]
It would be nice to have an option to update the previous summary comment on Pull requests instead of adding a new comment. Since tests can run on multiple commits, adding a new comment everytime can get messy.

**Comment by ciandt-crodrigues** [comment]
@Ma11hewThomas  I was thinking on adding a PR to cover that.
using a hidden comment to know which comment is safe to remove, but the project loads with a ton of prettier errors here and I was afraid to change things there. that would not be the intent of the change.
Maybe you could clone the repo with a clean VSCode and see the error first?

If you are already working on this nevermind, I can wait.

**Comment by Ma11hewThomas** [comment]
Hey @ciandt-crodrigues, I'm in the process of refactoring the code to resolve these issues. Following this it will be easier to contribute. I'll pick this feature up as part of the refactoring, but keep an eye on open issues for more opportunities to contribute in the future. 

Thanks

**Comment by Ma11hewThomas** [comment]
See https://github.com/ctrf-io/github-test-reporter?tab=readme-ov-file#comment-management-inputs
