### ISSUE TITLE
Not able to get historical data

### ISSUE THREAD

**Issue by HarshadDGhorpade-eaton** [ctrf-io/github-test-reporter#57]
I would like to understand the need for the ctrf json file name as input while generating the historical data for the workflow which has workflow_dispatch/schedule event.

reference :  https://github.com/ctrf-io/github-test-reporter/actions/runs/11675501116/workflow#L32

why `ctrf-reports/ctrf-report-no-fails.json` is referred if we're giving custom artifact name ? I think this is pointing to json file in the repository under ctrf-reports directory.

with regard to this, I am getting below error while trying to get historical data :

------
+ npx junit-to-ctrf pytr.xml -o pytr.json
+ npx github-actions-ctrf historical pytr.json --artifact-name 'Test_Image dev-pytest'
Failed to read or process the file: Error: ENOENT: no such file or directory, open 'pytr.json'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at validateCtrfFile (/__w/github-builds/github-builds/node_modules/github-actions-ctrf/dist/common.js:11:42)
    at Object.<anonymous> (/__w/github-builds/github-builds/node_modules/github-actions-ctrf/dist/index.js:569:52)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'pytr.json'
}
Unable to generate GitHub Actions Summary, moving on without...

artifact named 'Test_Image dev-pytest' has 3 files in it, `pytr.html`, `pytr.xml`, `pytr.json`

I think I am missing something with the file path.

**Comment by Ma11hewThomas** [comment]
Hello @HarshadDGhorpade-eaton, 

The first argument for all reports is the path of the CTRF report from the current action. 

```bash
run: npx github-actions-ctrf path-to-your-ctrf-report.json
```

This is also true for the historical report, it appears that the report at root pytr.json can not be found, can you check that this file exists? 

In the example you refer to `ctrf-reports/ctrf-report-no-fails.json` is the current CTRF report.

**Comment by HarshadDGhorpade-eaton** [comment]
okay, that got me confused, its path to the locally generated ctrf json for that particular run and not to the one from artifacts it downloads to generate historical data.
thanks, closing the issue.
